name: Build Memory Cache Windows

# on:
#   push:
#     branches:
#       - dev
#   pull_request:
#     branches:
#       - dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'johnshaughnessy/Memory-Cache-Browser-Client'
        path: 'Memory-Cache-Browser-Client'

    - name: Install Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.2'

    - name: Install Memory Cache Browser Client Dependencies
      run: |
        cd Memory-Cache-Browser-Client
        corepack enable
        yarn --version
        yarn install

    - name: Build Memory Cache Browser Client
      run: |
        cd Memory-Cache-Browser-Client
        yarn parcel build src/index.html

    - uses: actions/checkout@v2
      with:
        repository: 'johnshaughnessy/Memory-Cache-Hub'
        path: 'Memory-Cache-Hub'

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Memory Cache Hub Dependencies
      run: |
        cd Memory-Cache-Hub
        python -m venv venv
        venv\Scripts\activate
        pip install -r requirements.txt

    - name: Build Memory Cache Hub
      run: |
        cd Memory-Cache-Hub
        venv\Scripts\activate
        pip install -r requirements.build.txt
        python -m memory_cache_hub.build.build_memory_cache_hub --client-path ../Memory-Cache-Browser-Client/dist

    - name: Zip the Memory Cache Hub Build
      shell: powershell
      run: |
        Compress-Archive -Path Memory-Cache-Hub\dist\memory_cache_hub\* -DestinationPath Memory-Cache-Hub\dist\memory_cache_hub.zip -Force

    - name: Upload Memory Cache Hub Artifact
      uses: actions/upload-artifact@v2
      with:
        name: memory_cache_${{ runner.os }}_${{ github.sha }}
        path: Memory-Cache-Hub\dist\memory_cache_hub.zip
